--------------------------------------------------------
-- Archivo creado  - viernes-julio-10-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CINE
--------------------------------------------------------

  CREATE TABLE "TDIGITAL"."CINE" 
   (	"ID_CINE" VARCHAR2(10 BYTE), 
	"NOM_CINE" VARCHAR2(100 BYTE), 
	"DIRECCION" VARCHAR2(255 BYTE), 
	"TELEFONO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into TDIGITAL.CINE
SET DEFINE OFF;
Insert into TDIGITAL.CINE (ID_CINE,NOM_CINE,DIRECCION,TELEFONO) values ('cine1','hoyts','lejos','123456');
Insert into TDIGITAL.CINE (ID_CINE,NOM_CINE,DIRECCION,TELEFONO) values ('cine2','cineplanet','maslejos','987654');
Insert into TDIGITAL.CINE (ID_CINE,NOM_CINE,DIRECCION,TELEFONO) values ('cine3','cinemark','cerca','743632764');
--------------------------------------------------------
--  DDL for Index CINE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TDIGITAL"."CINE_PK" ON "TDIGITAL"."CINE" ("ID_CINE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CINE
--------------------------------------------------------

  ALTER TABLE "TDIGITAL"."CINE" ADD CONSTRAINT "CINE_PK" PRIMARY KEY ("ID_CINE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TDIGITAL"."CINE" MODIFY ("ID_CINE" NOT NULL ENABLE);
