--------------------------------------------------------
-- Archivo creado  - viernes-julio-10-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DET_SALA
--------------------------------------------------------

  CREATE TABLE "TDIGITAL"."DET_SALA" 
   (	"ID_SALA" VARCHAR2(10 BYTE), 
	"ID_CINE" VARCHAR2(10 BYTE), 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"NUM_SALA" VARCHAR2(10 BYTE), 
	"CANT_BUT" VARCHAR2(10 BYTE), 
	"PELICULA_ID_PELICULA" VARCHAR2(10 BYTE), 
	"CINE_ID_CINE" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into TDIGITAL.DET_SALA
SET DEFINE OFF;
Insert into TDIGITAL.DET_SALA (ID_SALA,ID_CINE,NOMBRE,NUM_SALA,CANT_BUT,PELICULA_ID_PELICULA,CINE_ID_CINE) values ('SA1','cine1','salaA','A1','80','1','cine1');
Insert into TDIGITAL.DET_SALA (ID_SALA,ID_CINE,NOMBRE,NUM_SALA,CANT_BUT,PELICULA_ID_PELICULA,CINE_ID_CINE) values ('SA2','cine1','salaB','A2','100','2','cine1');
Insert into TDIGITAL.DET_SALA (ID_SALA,ID_CINE,NOMBRE,NUM_SALA,CANT_BUT,PELICULA_ID_PELICULA,CINE_ID_CINE) values ('SA3','cine1','salaC','A3','120','3','cine1');
Insert into TDIGITAL.DET_SALA (ID_SALA,ID_CINE,NOMBRE,NUM_SALA,CANT_BUT,PELICULA_ID_PELICULA,CINE_ID_CINE) values ('SB1','cine2','salaA','B1','80','1','cine2');
Insert into TDIGITAL.DET_SALA (ID_SALA,ID_CINE,NOMBRE,NUM_SALA,CANT_BUT,PELICULA_ID_PELICULA,CINE_ID_CINE) values ('SB2','cine2','salaB','B2','100','2','cine2');
Insert into TDIGITAL.DET_SALA (ID_SALA,ID_CINE,NOMBRE,NUM_SALA,CANT_BUT,PELICULA_ID_PELICULA,CINE_ID_CINE) values ('SB3','cine2','salaC','B3','120','3','cine2');
Insert into TDIGITAL.DET_SALA (ID_SALA,ID_CINE,NOMBRE,NUM_SALA,CANT_BUT,PELICULA_ID_PELICULA,CINE_ID_CINE) values ('SA1','cine3','salaA','C1','80','1','cine3');
Insert into TDIGITAL.DET_SALA (ID_SALA,ID_CINE,NOMBRE,NUM_SALA,CANT_BUT,PELICULA_ID_PELICULA,CINE_ID_CINE) values ('SC2','cine3','salaB','C2','100','2','cine3');
Insert into TDIGITAL.DET_SALA (ID_SALA,ID_CINE,NOMBRE,NUM_SALA,CANT_BUT,PELICULA_ID_PELICULA,CINE_ID_CINE) values ('SC3','cine3','salaC','C3','120','3','cine3');
--------------------------------------------------------
--  DDL for Index DET_SALA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TDIGITAL"."DET_SALA_PK" ON "TDIGITAL"."DET_SALA" ("ID_SALA", "ID_CINE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table DET_SALA
--------------------------------------------------------

  ALTER TABLE "TDIGITAL"."DET_SALA" ADD CONSTRAINT "DET_SALA_PK" PRIMARY KEY ("ID_SALA", "ID_CINE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TDIGITAL"."DET_SALA" MODIFY ("CINE_ID_CINE" NOT NULL ENABLE);
  ALTER TABLE "TDIGITAL"."DET_SALA" MODIFY ("PELICULA_ID_PELICULA" NOT NULL ENABLE);
  ALTER TABLE "TDIGITAL"."DET_SALA" MODIFY ("ID_CINE" NOT NULL ENABLE);
  ALTER TABLE "TDIGITAL"."DET_SALA" MODIFY ("ID_SALA" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table DET_SALA
--------------------------------------------------------

  ALTER TABLE "TDIGITAL"."DET_SALA" ADD CONSTRAINT "DET_SALA_CINE_FK" FOREIGN KEY ("CINE_ID_CINE")
	  REFERENCES "TDIGITAL"."CINE" ("ID_CINE") ENABLE;
  ALTER TABLE "TDIGITAL"."DET_SALA" ADD CONSTRAINT "DET_SALA_PELICULA_FK" FOREIGN KEY ("PELICULA_ID_PELICULA")
	  REFERENCES "TDIGITAL"."PELICULA" ("ID_PELICULA") ENABLE;
