--------------------------------------------------------
-- Archivo creado  - viernes-julio-10-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table FUNCION
--------------------------------------------------------

  CREATE TABLE "TDIGITAL"."FUNCION" 
   (	"ID_SALA" VARCHAR2(10 BYTE), 
	"FECHA_FUNC" DATE, 
	"HORA_FUNC" DATE, 
	"ID_PELICULA" VARCHAR2(10 BYTE), 
	"ID_FUNCION" VARCHAR2(10 BYTE), 
	"PELICULA_ID_PELICULA" VARCHAR2(10 BYTE), 
	"DET_SALA_ID_SALA" VARCHAR2(10 BYTE), 
	"DET_SALA_ID_CINE" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into TDIGITAL.FUNCION
SET DEFINE OFF;
Insert into TDIGITAL.FUNCION (ID_SALA,FECHA_FUNC,HORA_FUNC,ID_PELICULA,ID_FUNCION,PELICULA_ID_PELICULA,DET_SALA_ID_SALA,DET_SALA_ID_CINE) values ('SA1',to_date('09/07/20','DD/MM/RR'),to_date('09/07/20','DD/MM/RR'),'1','F1','1','SA1','cine1');
Insert into TDIGITAL.FUNCION (ID_SALA,FECHA_FUNC,HORA_FUNC,ID_PELICULA,ID_FUNCION,PELICULA_ID_PELICULA,DET_SALA_ID_SALA,DET_SALA_ID_CINE) values ('SB2',to_date('09/07/20','DD/MM/RR'),to_date('09/07/20','DD/MM/RR'),'2','F2','2','SB2','cine2');
Insert into TDIGITAL.FUNCION (ID_SALA,FECHA_FUNC,HORA_FUNC,ID_PELICULA,ID_FUNCION,PELICULA_ID_PELICULA,DET_SALA_ID_SALA,DET_SALA_ID_CINE) values ('SC3',to_date('09/07/20','DD/MM/RR'),to_date('09/07/20','DD/MM/RR'),'3','F3','3','SC3','cine3');
--------------------------------------------------------
--  DDL for Index FUNCION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TDIGITAL"."FUNCION_PK" ON "TDIGITAL"."FUNCION" ("ID_PELICULA", "ID_FUNCION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table FUNCION
--------------------------------------------------------

  ALTER TABLE "TDIGITAL"."FUNCION" ADD CONSTRAINT "FUNCION_PK" PRIMARY KEY ("ID_PELICULA", "ID_FUNCION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TDIGITAL"."FUNCION" MODIFY ("DET_SALA_ID_CINE" NOT NULL ENABLE);
  ALTER TABLE "TDIGITAL"."FUNCION" MODIFY ("DET_SALA_ID_SALA" NOT NULL ENABLE);
  ALTER TABLE "TDIGITAL"."FUNCION" MODIFY ("PELICULA_ID_PELICULA" NOT NULL ENABLE);
  ALTER TABLE "TDIGITAL"."FUNCION" MODIFY ("ID_FUNCION" NOT NULL ENABLE);
  ALTER TABLE "TDIGITAL"."FUNCION" MODIFY ("ID_PELICULA" NOT NULL ENABLE);
  ALTER TABLE "TDIGITAL"."FUNCION" MODIFY ("ID_SALA" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table FUNCION
--------------------------------------------------------

  ALTER TABLE "TDIGITAL"."FUNCION" ADD CONSTRAINT "FUNCION_DET_SALA_FK" FOREIGN KEY ("DET_SALA_ID_SALA", "DET_SALA_ID_CINE")
	  REFERENCES "TDIGITAL"."DET_SALA" ("ID_SALA", "ID_CINE") ENABLE;
  ALTER TABLE "TDIGITAL"."FUNCION" ADD CONSTRAINT "FUNCION_PELICULA_FK" FOREIGN KEY ("PELICULA_ID_PELICULA")
	  REFERENCES "TDIGITAL"."PELICULA" ("ID_PELICULA") ENABLE;
