--------------------------------------------------------
-- Archivo creado  - viernes-julio-10-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PELICULA
--------------------------------------------------------

  CREATE TABLE "TDIGITAL"."PELICULA" 
   (	"ID_PELICULA" VARCHAR2(10 BYTE), 
	"TIT_DIST" VARCHAR2(50 BYTE), 
	"TIT_ORIG" VARCHAR2(50 BYTE), 
	"PAIS_ORIGEN" VARCHAR2(30 BYTE), 
	"ANO_PROD" NUMBER(4,0), 
	"WEB" VARCHAR2(50 BYTE), 
	"DURACION" VARCHAR2(8 BYTE), 
	"FECHA_EST" DATE, 
	"RESUMEN" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into TDIGITAL.PELICULA
SET DEFINE OFF;
Insert into TDIGITAL.PELICULA (ID_PELICULA,TIT_DIST,TIT_ORIG,PAIS_ORIGEN,ANO_PROD,WEB,DURACION,FECHA_EST,RESUMEN) values ('1','abc','abc1','chile','1990','www.abc.cl','220',to_date('09/07/92','DD/MM/RR'),'es bacan');
Insert into TDIGITAL.PELICULA (ID_PELICULA,TIT_DIST,TIT_ORIG,PAIS_ORIGEN,ANO_PROD,WEB,DURACION,FECHA_EST,RESUMEN) values ('2','def','def1','china','1993','www.def.cn','200',to_date('09/07/20','DD/MM/RR'),'no se cacha');
Insert into TDIGITAL.PELICULA (ID_PELICULA,TIT_DIST,TIT_ORIG,PAIS_ORIGEN,ANO_PROD,WEB,DURACION,FECHA_EST,RESUMEN) values ('3','ghi','ghi1','peru','1995','www.ghi.pe','120',to_date('15/07/95','DD/MM/RR'),'peru pe');
--------------------------------------------------------
--  DDL for Index PELICULA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TDIGITAL"."PELICULA_PK" ON "TDIGITAL"."PELICULA" ("ID_PELICULA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PELICULA
--------------------------------------------------------

  ALTER TABLE "TDIGITAL"."PELICULA" ADD CONSTRAINT "PELICULA_PK" PRIMARY KEY ("ID_PELICULA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TDIGITAL"."PELICULA" MODIFY ("ID_PELICULA" NOT NULL ENABLE);
