--------------------------------------------------------
-- Archivo creado  - viernes-julio-10-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table REP_PELIC
--------------------------------------------------------

  CREATE TABLE "TDIGITAL"."REP_PELIC" 
   (	"ID_PELICULA" VARCHAR2(10 BYTE), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"ROL" VARCHAR2(50 BYTE), 
	"PELICULA_ID_PELICULA" VARCHAR2(10 BYTE), 
	"REP_INFO_NOMBRE" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into TDIGITAL.REP_PELIC
SET DEFINE OFF;
Insert into TDIGITAL.REP_PELIC (ID_PELICULA,NOMBRE,ROL,PELICULA_ID_PELICULA,REP_INFO_NOMBRE) values ('1','a','malo','1','a');
Insert into TDIGITAL.REP_PELIC (ID_PELICULA,NOMBRE,ROL,PELICULA_ID_PELICULA,REP_INFO_NOMBRE) values ('2','b','prota','2','b');
Insert into TDIGITAL.REP_PELIC (ID_PELICULA,NOMBRE,ROL,PELICULA_ID_PELICULA,REP_INFO_NOMBRE) values ('3','a','super','3','c');
--------------------------------------------------------
--  DDL for Index REP_PELIC__IDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "TDIGITAL"."REP_PELIC__IDX" ON "TDIGITAL"."REP_PELIC" ("PELICULA_ID_PELICULA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index REP_PELIC__IDXV1
--------------------------------------------------------

  CREATE UNIQUE INDEX "TDIGITAL"."REP_PELIC__IDXV1" ON "TDIGITAL"."REP_PELIC" ("REP_INFO_NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index REP_PELIC_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TDIGITAL"."REP_PELIC_PK" ON "TDIGITAL"."REP_PELIC" ("ID_PELICULA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table REP_PELIC
--------------------------------------------------------

  ALTER TABLE "TDIGITAL"."REP_PELIC" ADD CONSTRAINT "REP_PELIC_PK" PRIMARY KEY ("ID_PELICULA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TDIGITAL"."REP_PELIC" MODIFY ("REP_INFO_NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "TDIGITAL"."REP_PELIC" MODIFY ("PELICULA_ID_PELICULA" NOT NULL ENABLE);
  ALTER TABLE "TDIGITAL"."REP_PELIC" MODIFY ("ID_PELICULA" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table REP_PELIC
--------------------------------------------------------

  ALTER TABLE "TDIGITAL"."REP_PELIC" ADD CONSTRAINT "REP_PELIC_PELICULA_FK" FOREIGN KEY ("PELICULA_ID_PELICULA")
	  REFERENCES "TDIGITAL"."PELICULA" ("ID_PELICULA") ENABLE;
  ALTER TABLE "TDIGITAL"."REP_PELIC" ADD CONSTRAINT "REP_PELIC_REP_INFO_FK" FOREIGN KEY ("REP_INFO_NOMBRE")
	  REFERENCES "TDIGITAL"."REP_INFO" ("NOMBRE") ENABLE;
