--------------------------------------------------------
-- Archivo creado  - viernes-julio-10-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table REP_INFO
--------------------------------------------------------

  CREATE TABLE "TDIGITAL"."REP_INFO" 
   (	"NOMBRE" VARCHAR2(40 BYTE), 
	"NACIONALIDAD" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into TDIGITAL.REP_INFO
SET DEFINE OFF;
Insert into TDIGITAL.REP_INFO (NOMBRE,NACIONALIDAD) values ('a','1');
Insert into TDIGITAL.REP_INFO (NOMBRE,NACIONALIDAD) values ('b','2');
Insert into TDIGITAL.REP_INFO (NOMBRE,NACIONALIDAD) values ('c','3');
--------------------------------------------------------
--  DDL for Index REP_INFO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TDIGITAL"."REP_INFO_PK" ON "TDIGITAL"."REP_INFO" ("NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table REP_INFO
--------------------------------------------------------

  ALTER TABLE "TDIGITAL"."REP_INFO" ADD CONSTRAINT "REP_INFO_PK" PRIMARY KEY ("NOMBRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TDIGITAL"."REP_INFO" MODIFY ("NOMBRE" NOT NULL ENABLE);
