--------------------------------------------------------
-- Archivo creado  - viernes-julio-10-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SUBTITULOS
--------------------------------------------------------

  CREATE TABLE "TDIGITAL"."SUBTITULOS" 
   (	"ID_PELICULA" VARCHAR2(10 BYTE), 
	"SUBTITULOS" VARCHAR2(30 BYTE), 
	"PELICULA_ID_PELICULA" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into TDIGITAL.SUBTITULOS
SET DEFINE OFF;
Insert into TDIGITAL.SUBTITULOS (ID_PELICULA,SUBTITULOS,PELICULA_ID_PELICULA) values ('1','ES','1');
Insert into TDIGITAL.SUBTITULOS (ID_PELICULA,SUBTITULOS,PELICULA_ID_PELICULA) values ('2','EN','2');
Insert into TDIGITAL.SUBTITULOS (ID_PELICULA,SUBTITULOS,PELICULA_ID_PELICULA) values ('3','EN','3');
--------------------------------------------------------
--  DDL for Index SUBTITULOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TDIGITAL"."SUBTITULOS_PK" ON "TDIGITAL"."SUBTITULOS" ("ID_PELICULA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table SUBTITULOS
--------------------------------------------------------

  ALTER TABLE "TDIGITAL"."SUBTITULOS" ADD CONSTRAINT "SUBTITULOS_PK" PRIMARY KEY ("ID_PELICULA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TDIGITAL"."SUBTITULOS" MODIFY ("PELICULA_ID_PELICULA" NOT NULL ENABLE);
  ALTER TABLE "TDIGITAL"."SUBTITULOS" MODIFY ("ID_PELICULA" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table SUBTITULOS
--------------------------------------------------------

  ALTER TABLE "TDIGITAL"."SUBTITULOS" ADD CONSTRAINT "SUBTITULOS_PELICULA_FK" FOREIGN KEY ("PELICULA_ID_PELICULA")
	  REFERENCES "TDIGITAL"."PELICULA" ("ID_PELICULA") ENABLE;
